#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [ -f step1/linuxamd64_12102_database_1of2.zip -a -f step1/linuxamd64_12102_database_2of2.zip ]
then
  docker build -t oracle-12c:step1 step1
  docker run --privileged --name step1 oracle-12c:step1
  docker commit step1 oracle-12c:installed
  docker build -t oracle-12c:step2 step2
  docker run --privileged --name step2 oracle-12c:step2
  docker commit step2 oracle-12c:created
  docker build -t oracle-12c step3
else
  echo "Oracle install files are required in step1 directory"
fi
