#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

mount -t tmpfs shmfs -o size=4g /dev/shm

date
su -s /bin/bash oracle -c "cd /tmp/install/database/ && ./runInstaller -ignoreSysPrereqs -ignorePrereq -silent -noconfig -waitforcompletion -responseFile /tmp/db_install.rsp"
