
--  Creating users
CREATE USER &ZE_DATA_USR IDENTIFIED BY &ZE_DATA_PWD
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO &ZE_DATA_USR;
GRANT CREATE TABLE TO &ZE_DATA_USR;
GRANT CREATE PROCEDURE TO &ZE_DATA_USR;
GRANT CREATE VIEW TO &ZE_DATA_USR;
GRANT CREATE SYNONYM TO &ZE_DATA_USR;
GRANT CREATE SEQUENCE TO &ZE_DATA_USR;
GRANT CREATE TRIGGER TO &ZE_DATA_USR;

CREATE USER &ZE_VIEW_USR IDENTIFIED BY &ZE_VIEW_PWD
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO &ZE_VIEW_USR;
GRANT CREATE VIEW TO &ZE_VIEW_USR;
GRANT CREATE SYNONYM TO &ZE_VIEW_USR;
GRANT CREATE SEQUENCE TO &ZE_VIEW_USR;
GRANT CREATE TRIGGER TO &ZE_VIEW_USR;
GRANT CREATE PROCEDURE TO &ZE_VIEW_USR;

CREATE USER &ZE_UTL_USR IDENTIFIED BY &ZE_UTL_PWD
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO &ZE_UTL_USR;
GRANT CREATE TABLE TO &ZE_UTL_USR;
GRANT CREATE PROCEDURE TO &ZE_UTL_USR;
GRANT CREATE VIEW TO &ZE_UTL_USR;
GRANT CREATE SYNONYM TO &ZE_UTL_USR;
GRANT CREATE SEQUENCE TO &ZE_UTL_USR;
GRANT CREATE TRIGGER TO &ZE_UTL_USR;
GRANT CREATE TYPE TO &ZE_UTL_USR;

CREATE USER &ZE_METADATA_USR IDENTIFIED BY &ZE_METADATA_PWD
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO &ZE_METADATA_USR;
GRANT CREATE TABLE TO &ZE_METADATA_USR;
GRANT CREATE PROCEDURE TO &ZE_METADATA_USR;
GRANT CREATE VIEW TO &ZE_METADATA_USR;
GRANT CREATE SYNONYM TO &ZE_METADATA_USR;
GRANT CREATE SEQUENCE TO &ZE_METADATA_USR;
GRANT CREATE TRIGGER TO &ZE_METADATA_USR;
GRANT CREATE TYPE TO &ZE_METADATA_USR;
GRANT CREATE SNAPSHOT TO &ZE_METADATA_USR;
GRANT ALTER SESSION TO &ZE_METADATA_USR;

CREATE USER &ZE_SECURITY_V3_USR IDENTIFIED BY &ZE_SECURITY_V3_PWD
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO &ZE_SECURITY_V3_USR;
GRANT CREATE TABLE TO &ZE_SECURITY_V3_USR;
GRANT CREATE PROCEDURE TO &ZE_SECURITY_V3_USR;
GRANT CREATE VIEW TO &ZE_SECURITY_V3_USR;
GRANT CREATE SYNONYM TO &ZE_SECURITY_V3_USR;
GRANT CREATE SEQUENCE TO &ZE_SECURITY_V3_USR;
GRANT CREATE TRIGGER TO &ZE_SECURITY_V3_USR;

CREATE USER &ZE_CURVE_USR IDENTIFIED BY &ZE_CURVE_PWD
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO &ZE_CURVE_USR;
GRANT CREATE TABLE TO &ZE_CURVE_USR;
GRANT CREATE PROCEDURE TO &ZE_CURVE_USR;
GRANT CREATE VIEW TO &ZE_CURVE_USR;
GRANT CREATE SYNONYM TO &ZE_CURVE_USR;
GRANT CREATE SEQUENCE TO &ZE_CURVE_USR;
GRANT CREATE TRIGGER TO &ZE_CURVE_USR;

CREATE USER &ZE_DASHBOARD_USR IDENTIFIED BY &ZE_DASHBOARD_PWD
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO &ZE_DASHBOARD_USR;
GRANT CREATE TABLE TO &ZE_DASHBOARD_USR;
GRANT CREATE PROCEDURE TO &ZE_DASHBOARD_USR;
GRANT CREATE VIEW TO &ZE_DASHBOARD_USR;
GRANT CREATE SYNONYM TO &ZE_DASHBOARD_USR;
GRANT CREATE SEQUENCE TO &ZE_DASHBOARD_USR;
GRANT CREATE TRIGGER TO &ZE_DASHBOARD_USR;
GRANT CREATE TYPE TO &ZE_DASHBOARD_USR;
GRANT CREATE SNAPSHOT TO &ZE_DASHBOARD_USR;
GRANT ALTER SESSION TO &ZE_DASHBOARD_USR;

CREATE USER &ZE_DV_USR IDENTIFIED BY &ZE_DV_PWD
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT TO &ZE_DV_USR;

GRANT CREATE PROCEDURE TO &ZE_DV_USR;
GRANT CREATE SEQUENCE TO &ZE_DV_USR;
GRANT CREATE SESSION TO &ZE_DV_USR;
GRANT CREATE SYNONYM TO &ZE_DV_USR;
GRANT CREATE TABLE TO &ZE_DV_USR;
GRANT CREATE TRIGGER TO &ZE_DV_USR;
GRANT CREATE VIEW TO &ZE_DV_USR;
GRANT CREATE JOB TO &ZE_DV_USR;
GRANT RESOURCE TO &ZE_DV_USR;

ALTER USER &ZE_DV_USR DEFAULT ROLE ALL;

CREATE USER &ZE_JOB_USR IDENTIFIED BY &ZE_JOB_PWD
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO &ZE_JOB_USR;
GRANT CREATE VIEW, CREATE JOB TO &ZE_JOB_USR;

CREATE USER &ZE_LOGGING_USR IDENTIFIED BY &ZE_LOGGING_PWD
    QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO &ZE_LOGGING_USR;
GRANT CREATE TABLE TO &ZE_LOGGING_USR;
GRANT CREATE PROCEDURE TO &ZE_LOGGING_USR;
GRANT CREATE VIEW TO &ZE_LOGGING_USR;
GRANT CREATE SYNONYM TO &ZE_LOGGING_USR;
GRANT CREATE SEQUENCE TO &ZE_LOGGING_USR;
GRANT CREATE TRIGGER TO &ZE_LOGGING_USR;

CREATE USER &ZE_UPDATE_USR IDENTIFIED BY &ZE_UPDATE_PWD
  QUOTA UNLIMITED ON USERS;
  
CREATE USER &ZE_DM_USR IDENTIFIED BY &ZE_DM_PWD -- added for DM4
    QUOTA UNLIMITED ON USERS;
 
GRANT CREATE SESSION TO &ZE_DM_USR;
GRANT CREATE TABLE TO &ZE_DM_USR;
GRANT CREATE PROCEDURE TO &ZE_DM_USR;
GRANT CREATE VIEW TO &ZE_DM_USR;
GRANT CREATE SYNONYM TO &ZE_DM_USR;
GRANT CREATE SEQUENCE TO &ZE_DM_USR;
GRANT CREATE TRIGGER TO &ZE_DM_USR;
 
CONNECT &SYS_USR/&SYS_PWD AS SYSDBA;

GRANT EXECUTE ON DBMS_LOCK TO &ZE_JOB_USR WITH GRANT OPTION;
GRANT EXECUTE ON DBMS_LOCK TO &ZE_METADATA_USR WITH GRANT OPTION;
GRANT SELECT ON V_$SESSION TO &ZE_METADATA_USR WITH GRANT OPTION;
GRANT SELECT ON V_$MYSTAT TO &ZE_METADATA_USR WITH GRANT OPTION;
GRANT SELECT ON V_$STATNAME TO &ZE_METADATA_USR WITH GRANT OPTION;
GRANT SELECT ON DBA_SEGMENTS TO &ZE_METADATA_USR WITH GRANT OPTION;

DISCONNECT;
 
