 
-- Create Liquibase user/tables
CREATE TABLE &ZE_UPDATE_USR..DATABASECHANGELOGLOCK (ID INTEGER NOT NULL, LOCKED NUMBER(1) NOT NULL, LOCKGRANTED TIMESTAMP, LOCKEDBY VARCHAR2(255), CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY (ID));
CREATE TABLE &ZE_UPDATE_USR..DATABASECHANGELOG (ID VARCHAR2(63) NOT NULL, AUTHOR VARCHAR2(63) NOT NULL, FILENAME VARCHAR2(200) NOT NULL, DATEEXECUTED TIMESTAMP NOT NULL, ORDEREXECUTED INTEGER NOT NULL, EXECTYPE VARCHAR2(10) NOT NULL, MD5SUM VARCHAR2(35), DESCRIPTION VARCHAR2(255), COMMENTS VARCHAR2(255), TAG VARCHAR2(255), LIQUIBASE VARCHAR2(20), CONSTRAINT PK_DATABASECHANGELOG PRIMARY KEY (ID, AUTHOR, FILENAME));

GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOGLOCK TO &ZE_DATA_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOGLOCK TO &ZE_VIEW_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOGLOCK TO &ZE_METADATA_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOGLOCK TO &ZE_SECURITY_V3_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOGLOCK TO &ZE_UTL_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOGLOCK TO &ZE_CURVE_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOGLOCK TO &ZE_DASHBOARD_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOGLOCK TO &ZE_DV_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOGLOCK TO &ZE_DM_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOGLOCK TO &ZE_JOB_USR;

GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOG TO &ZE_DATA_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOG TO &ZE_VIEW_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOG TO &ZE_METADATA_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOG TO &ZE_SECURITY_V3_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOG TO &ZE_UTL_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOG TO &ZE_CURVE_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOG TO &ZE_DASHBOARD_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOG TO &ZE_DV_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOG TO &ZE_DM_USR;
GRANT SELECT,INSERT,UPDATE,DELETE ON &ZE_UPDATE_USR..DATABASECHANGELOG TO &ZE_JOB_USR;

INSERT INTO &ZE_UPDATE_USR..DATABASECHANGELOGLOCK (ID,LOCKED) VALUES (1,0);
COMMIT;

 